#pragma config(Motor,  port1,           Right2,        tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port2,           Left1,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           Roller,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ClawArmL,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           TL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           TR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ClawArmR,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Mogo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Right1,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          Left2,         tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
		float ch3_drive;
		float ch1_drive;
		float a = vexRT[Ch3] / 127.0;
		float b = vexRT[Ch1] / 127.0;
		ch3_drive = (0.463* (pow(a,3))- (0.069 * pow(a,2)) + (0.614 * a) ) * 127;
		ch1_drive = (0.463* (pow(b,3))- (0.069 * pow(b,2)) + (0.614 * b) ) * 127;


		motor[Left1]  = ((ch3_drive) + (ch1_drive));
		motor[Left2]  = ((ch3_drive) + (ch1_drive));
		motor[Right1] = ((ch3_drive) - (ch1_drive));
		motor[Right2] = ((ch3_drive) - (ch1_drive));

//-------------------------------
		if ((vexRT [Btn6U] ==1)||(vexRT [Btn6UXmtr2] ==1)) {
			motor[ClawArmL] = motor[ClawArmR] = 120;

		}

		else if ((vexRT [Btn6D] ==1)||(vexRT [Btn6DXmtr2] ==1)){


			motor[ClawArmL] = motor[ClawArmR] = -120;
		}

		else {

			motor[ClawArmL] = motor[ClawArmR] = 0;
		}
//---------------------------------------------
		if((vexRT[Btn7U] == 1)||(vexRT[Btn5UXmtr2]==1))
		{

			motor [TL] = motor [TR] = 120;


		}
		else if((vexRT[Btn7D] == 1)||(vexRT[Btn5UXmtr2]==1))
		{

			motor [TL] = motor [TR] = -120;


		}

		else {
			motor [TL] = motor [TR] = 0;
		}
//------------------------------------------
		if (vexRT [Btn5D] ==1) {

			motor[Mogo] = 120;

		}

		else if ( vexRT [Btn5U] ==1) {
			motor[Mogo] = -120;
		}
		else {
			motor[Mogo] = 0;
		}

//---------------------------------------------
		if(vexRT[Btn7DXmtr2] == 1)
		{
			while((vexRT[Btn7DXmtr2] ==1)) {
				motor [Roller] = 120;

				wait1Msec (40);

			}
		}
		else if(vexRT[Btn8DXmtr2] == 1)
		{
			while(vexRT[Btn8DXmtr2] ==1) {
				motor [Roller] = -120;

				wait1Msec (40);

			}
		}

		else {
			motor [Roller] = 20;
		}



		wait1Msec(40);
	}
}
